// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: edge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ParkID        string                 `protobuf:"bytes,2,opt,name=parkID,proto3" json:"parkID,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Brightness    float32                `protobuf:"fixed32,5,opt,name=brightness,proto3" json:"brightness,omitempty"`
	AirQuality    float32                `protobuf:"fixed32,6,opt,name=air_quality,json=airQuality,proto3" json:"air_quality,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *SensorData) GetParkID() string {
	if x != nil {
		return x.ParkID
	}
	return ""
}

func (x *SensorData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorData) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *SensorData) GetAirQuality() float32 {
	if x != nil {
		return x.AirQuality
	}
	return 0
}

func (x *SensorData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_edge_proto protoreflect.FileDescriptor

const file_edge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"edge.proto\x12\x04edge\"\xdd\x01\n" +
	"\n" +
	"SensorData\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06parkID\x18\x02 \x01(\tR\x06parkID\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x02R\bhumidity\x12\x1e\n" +
	"\n" +
	"brightness\x18\x05 \x01(\x02R\n" +
	"brightness\x12\x1f\n" +
	"\vair_quality\x18\x06 \x01(\x02R\n" +
	"airQuality\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\">\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2=\n" +
	"\rSensorService\x12,\n" +
	"\bSendData\x12\x10.edge.SensorData\x1a\x0e.edge.ResponseB Z\x1eprogetto/server/go/proto;protob\x06proto3"

var (
	file_edge_proto_rawDescOnce sync.Once
	file_edge_proto_rawDescData []byte
)

func file_edge_proto_rawDescGZIP() []byte {
	file_edge_proto_rawDescOnce.Do(func() {
		file_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)))
	})
	return file_edge_proto_rawDescData
}

var file_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_edge_proto_goTypes = []any{
	(*SensorData)(nil), // 0: edge.SensorData
	(*Response)(nil),   // 1: edge.Response
}
var file_edge_proto_depIdxs = []int32{
	0, // 0: edge.SensorService.SendData:input_type -> edge.SensorData
	1, // 1: edge.SensorService.SendData:output_type -> edge.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_edge_proto_init() }
func file_edge_proto_init() {
	if File_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edge_proto_goTypes,
		DependencyIndexes: file_edge_proto_depIdxs,
		MessageInfos:      file_edge_proto_msgTypes,
	}.Build()
	File_edge_proto = out.File
	file_edge_proto_goTypes = nil
	file_edge_proto_depIdxs = nil
}
